
services:
  frontend:
    build:
      context: .
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "8080:80"
    networks:
      - dishcovery-network

networks:
  dishcovery-network:
    external: 
      name: dishcovery-network
